language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    update: true
    brewfile: true

  # apt:
  #   packages:
  #     - oracle-java8-installer
      # - openjdk-8-jre-headless
      # - oracle-java8-installer

# jdk:
  # - oraclejdk8
  # - oraclejdk11
  # - openjdk8
# jdk:
#   - oraclejdk8

# env:
#   - JAVA_HOME="1.0.*"

cache:
  directories:
  - buck-out/cache

before_install:
  # - rvm use $RVM_RUBY_VERSION
  # - export JAVA_HOME=$(/usr/libexec/java_home)
  # - export JAVA_HOME=$HOME/openjdk8
  # - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - bundle install
  # - brew tap caskroom/cask
  # - brew tap caskroom/versions
  # - brew cask install java8
  - gem install xcpretty-travis-formatter;
  #- gem install cocoapods -v '1.3.1' --no-document --quiet;
  # - gem install slather --no-document --quiet;  
  - bundle exec pod install --repo-update;
  # - carthage bootstrap --verbose --platform iOS --cache-builds --use-ssh 

script:
  # - jdk_switcher use openjdk8
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11 -L GPL
  - install-jdk.sh -F 8
  - buck test :yoga
  - set -o pipefail && bundle exec fastlane travis

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FlexLayout' -J 'FlexLayoutTests'
