language: objective-c
osx_image: xcode8.3

env:
  matrix:
    - SCHEME=FlexLayout       SDK=iphonesimulator10.3
    - SCHEME=FlexLayoutSample SDK=iphonesimulator10.3

before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;
  - gem install slather --no-document --quiet;  
  - pod install --repo-update;

script:
  - |
    if [[ $SCHEME = "FlexLayout" ]]; then
      set -o pipefail && xcodebuild -workspace FlexLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES build test | xcpretty -f `xcpretty-travis-formatter`
    fi

    if [[ $SCHEME = "FlexLayoutSample" ]]; then
      set -o pipefail && xcodebuild -workspace FlexLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination 'platform=iOS Simulator,name=iPhone 6' build | xcpretty -f `xcpretty-travis-formatter`
    fi

after_success:
  - |
    if [[ $SCHEME = "FlexLayout" ]]; then
      slather coverage -s --workspace FlexLayout.xcworkspace --scheme FlexLayout --coveralls --travis FlexLayout.xcodeproj
    fi

