language: objective-c
osx_image: xcode9

env:
  matrix:
    - SCHEME=FlexLayout       SDK=iphonesimulator11.0
    - SCHEME=FlexLayout       SDK=iphonesimulator10.3
    - SCHEME=FlexLayoutSample SDK=iphonesimulator11.0

before_install:
  - rvm use $RVM_RUBY_VERSION
  # - bundle install
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods -v '1.3.1' --no-document --quiet;
  - gem install slather --no-document --quiet;  
  - pod install --repo-update;
  # - carthage bootstrap --verbose --platform iOS --cache-builds --use-ssh 

script:
  - |
    if [[ $SCHEME = "FlexLayout" ]]; then
      set -o pipefail && xcodebuild -workspace FlexLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES build test | xcpretty -f `xcpretty-travis-formatter`
    fi

    if [[ $SCHEME = "FlexLayoutSample" ]]; then
      set -o pipefail && xcodebuild -workspace FlexLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination 'platform=iOS Simulator,name=iPhone 6' build | xcpretty -f `xcpretty-travis-formatter`
    fi

after_success:
  - |
    if [[ $SCHEME = "FlexLayout" ]]; then
      slather coverage -s --workspace FlexLayout.xcworkspace --scheme FlexLayout --coveralls --travis FlexLayout.xcodeproj
    fi

